In [24]:
import tensorflow as tf
from tensorflow.keras import datasets,models,layers
import numpy as np
import matplotlib.pyplot as plt


In [5]:
(X_train,y_train),(X_test,y_test)= datasets.cifar10.load_data()

170508288/170498071 [==============================] - 35s 0us/step


In [6]:
X_train.shape

(50000, 32, 32, 3)

In [7]:
X_test.shape

(10000, 32, 32, 3)

In [9]:
X_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [10]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [11]:
y_train=y_train.reshape(-1,)

In [12]:
X_train=X_train/255
X_test=X_test/255

In [15]:
model=models.Sequential([
    keras.layers.Flatten(input_shape=(32,32,3)),
    keras.layers.Dense(3000, activation='relu'),
    keras.layers.Dense(1000, activation='relu'),
    keras.layers.Dense(3000, activation='sigmoid')
    
])

In [18]:
model.compile(optimizer='SGD',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1563/1563 [==============================] - 61s 39ms/step - loss: 1.9978 - accuracy: 0.3001
Epoch 2/5
1563/1563 [==============================] - 61s 39ms/step - loss: 1.7154 - accuracy: 0.3942
Epoch 3/5
1563/1563 [==============================] - 59s 38ms/step - loss: 1.6153 - accuracy: 0.4284
Epoch 4/5
1563/1563 [==============================] - 60s 38ms/step - loss: 1.5506 - accuracy: 0.4519
Epoch 5/5
1563/1563 [==============================] - 62s 40ms/step - loss: 1.5001 - accuracy: 0.4697


In [20]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred=model.predict(X_test)
y_pred_classes= [np.argmax(x) for x in y_pred]
print(classification_report(y_test,y_pred_classes))

              precision    recall  f1-score   support

           0       0.29      0.56      0.38      1000
           1       0.46      0.56      0.51      1000
           2       0.23      0.39      0.29      1000
           3       0.34      0.16      0.22      1000
           4       0.29      0.42      0.35      1000
           5       0.20      0.09      0.12      1000
           6       0.42      0.38      0.40      1000
           7       0.61      0.24      0.35      1000
           8       0.37      0.48      0.42      1000
           9       0.77      0.15      0.25      1000

    accuracy                           0.34     10000
   macro avg       0.40      0.34      0.33     10000
weighted avg       0.40      0.34      0.33     10000



In [25]:
cnn=models.Sequential([
        layers.Conv2D(filters=32,activation='relu',kernel_size=(3,3),input_shape=(32,32,3)),
        layers.MaxPooling2D((2,2)),
    
        layers.Conv2D(filters=64,activation='relu',kernel_size=(3,3)),
        layers.MaxPooling2D((2,2)),
    
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dense(10, activation='softmax')
    
])

In [27]:
cnn.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [28]:
cnn.fit(X_train,y_train,epochs=10)

Epoch 1/10
1563/1563 [==============================] - 23s 14ms/step - loss: 1.4773 - accuracy: 0.4688
Epoch 2/10
1563/1563 [==============================] - 22s 14ms/step - loss: 1.1368 - accuracy: 0.5986
Epoch 3/10
1563/1563 [==============================] - 22s 14ms/step - loss: 1.0069 - accuracy: 0.6484
Epoch 4/10
1563/1563 [==============================] - 22s 14ms/step - loss: 0.9245 - accuracy: 0.6771
Epoch 5/10
1563/1563 [==============================] - 22s 14ms/step - loss: 0.8638 - accuracy: 0.6977
Epoch 6/10
1563/1563 [==============================] - 22s 14ms/step - loss: 0.8096 - accuracy: 0.7162
Epoch 7/10
1563/1563 [==============================] - 21s 14ms/step - loss: 0.7584 - accuracy: 0.7336
Epoch 8/10
1563/1563 [==============================] - 21s 13ms/step - loss: 0.7158 - accuracy: 0.7484
Epoch 9/10
1563/1563 [==============================] - 24s 16ms/step - loss: 0.6756 - accuracy: 0.7611
Epoch 10/10
1563/1563 [==============================] - 21s 13m

In [29]:
cnn.evaluate(X_test,y_test)

313/313 [==============================] - 5s 7ms/step - loss: 0.9828 - accuracy: 0.6728


[0.9827799797058105, 0.6728000044822693]

In [30]:
y_test=y_test.reshape(-1)

In [31]:
y_test

array([3, 8, 8, ..., 5, 1, 7], dtype=uint8)

In [32]:
y_pred=cnn.predict(X_test)

In [33]:
y_pred_classes=[np.argmax(x) for x in y_pred]

In [34]:
y_pred_classes

[3,
 8,
 8,
 0,
 4,
 6,
 1,
 3,
 3,
 1,
 0,
 9,
 5,
 7,
 9,
 8,
 5,
 7,
 8,
 5,
 3,
 0,
 0,
 9,
 4,
 4,
 4,
 0,
 9,
 6,
 3,
 5,
 4,
 5,
 9,
 3,
 7,
 9,
 9,
 5,
 4,
 6,
 5,
 6,
 0,
 9,
 3,
 3,
 7,
 2,
 9,
 8,
 7,
 3,
 0,
 8,
 7,
 5,
 5,
 3,
 7,
 5,
 4,
 2,
 5,
 2,
 1,
 0,
 3,
 7,
 0,
 3,
 8,
 8,
 9,
 2,
 0,
 5,
 3,
 8,
 8,
 1,
 1,
 7,
 3,
 7,
 4,
 8,
 8,
 9,
 0,
 3,
 8,
 6,
 4,
 6,
 4,
 0,
 0,
 3,
 4,
 7,
 6,
 3,
 1,
 1,
 3,
 6,
 3,
 5,
 4,
 0,
 2,
 2,
 1,
 3,
 4,
 4,
 2,
 5,
 8,
 3,
 1,
 2,
 8,
 0,
 0,
 3,
 5,
 0,
 2,
 1,
 8,
 9,
 1,
 5,
 9,
 7,
 2,
 8,
 3,
 5,
 6,
 5,
 8,
 7,
 6,
 5,
 7,
 3,
 8,
 1,
 6,
 0,
 0,
 5,
 6,
 9,
 3,
 4,
 0,
 1,
 5,
 6,
 0,
 7,
 8,
 4,
 9,
 0,
 9,
 9,
 9,
 8,
 9,
 9,
 3,
 7,
 3,
 0,
 0,
 5,
 2,
 3,
 5,
 8,
 6,
 3,
 3,
 0,
 5,
 3,
 0,
 1,
 7,
 2,
 9,
 8,
 7,
 8,
 5,
 0,
 8,
 7,
 1,
 3,
 8,
 5,
 7,
 9,
 5,
 0,
 5,
 9,
 8,
 0,
 7,
 9,
 0,
 7,
 7,
 3,
 9,
 4,
 3,
 9,
 3,
 2,
 3,
 3,
 5,
 1,
 5,
 1,
 8,
 0,
 4,
 9,
 5,
 5,
 1,
 1,
 8,
 9,
 0,
 8,
 1,
 8,
 2,
 0,


In [35]:
classification_report(y_test,y_pred_classes)

'              precision    recall  f1-score   support\n\n           0       0.71      0.76      0.73      1000\n           1       0.81      0.82      0.81      1000\n           2       0.68      0.44      0.53      1000\n           3       0.42      0.59      0.49      1000\n           4       0.66      0.55      0.60      1000\n           5       0.50      0.70      0.58      1000\n           6       0.90      0.56      0.69      1000\n           7       0.77      0.73      0.75      1000\n           8       0.77      0.81      0.79      1000\n           9       0.77      0.79      0.78      1000\n\n    accuracy                           0.67     10000\n   macro avg       0.70      0.67      0.68     10000\nweighted avg       0.70      0.67      0.68     10000\n'